package br.com.contacerta.servicos;

import android.app.*;import android.os.*;import android.content.*;import android.database.*;import android.database.sqlite.*;import android.graphics.Color;import android.graphics.Typeface;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.widget.*;import java.io.*;import java.text.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity{
 static final int NAVY=Color.rgb(13,30,56), BG=Color.rgb(246,247,250), GOLD=Color.rgb(201,165,72), TEXT=Color.rgb(31,42,55), MUTED=Color.rgb(112,128,144);
 DB db; LinearLayout root,content,drawer; TextView title; int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);db.getWritableDatabase();buildShell();dashboard();}
 void buildShell(){FrameLayout frame=new FrameLayout(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);frame.addView(root,new FrameLayout.LayoutParams(-1,-1));
  LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(16),dp(10),dp(12),dp(10));bar.setBackgroundColor(NAVY);
  TextView ham=tv("☰",32,Color.WHITE);ham.setGravity(Gravity.CENTER);ham.setOnClickListener(v->openDrawer());bar.addView(ham,new LinearLayout.LayoutParams(dp(54),dp(62)));
  ImageView logo=new ImageView(this);logo.setImageResource(br.com.contacerta.servicos.R.drawable.logomarca);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);bar.addView(logo,new LinearLayout.LayoutParams(dp(58),dp(58)));
  LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.setPadding(dp(10),0,0,0);TextView a=tv("CONTA CERTA",22,Color.WHITE);a.setTypeface(null,Typeface.BOLD);TextView s=tv("Serviços Administrativos",15,Color.WHITE);s.setTypeface(null,Typeface.BOLD);brand.addView(a);brand.addView(s);bar.addView(brand,new LinearLayout.LayoutParams(0,dp(70),1));root.addView(bar);
  content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(16),dp(16),dp(16));ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  drawer=makeDrawer();drawer.setVisibility(View.GONE);FrameLayout.LayoutParams dl=new FrameLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.78),-1);dl.gravity=Gravity.LEFT;frame.addView(drawer,dl);setContentView(frame);
 }
 LinearLayout makeDrawer(){LinearLayout d=new LinearLayout(this);d.setOrientation(LinearLayout.VERTICAL);d.setBackgroundColor(NAVY);d.setPadding(dp(12),dp(24),dp(12),dp(8));ScrollView sv=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);
  String[][] m={{"🏠 Visão Geral","dash"},{"↓ Contas a Pagar","pagar"},{"└ Caixa Diário — Despesas","mov"},{"↑ Contas a Receber","receber"},{"└ Caixa Diário — Receitas","mov"},{"🛒 Nova Venda","vendas"},{"👥 Clientes / Participantes","clientes"},{"🚚 Fornecedores","fornecedores"},{"📦 Produtos / Estoque","produtos"},{"📚 Plano de Contas","plano_contas"},{"🎯 Centros de Custo","centros_custo"},{"🏦 Contas Financeiras","bancos"},{"🧾 Controle de Boletos","boletos"},{"💬 Controle de Fiado","fiado"},{"💳 Controle de Cheques","cheques_juros"},{"└ Juros de Cheques","cheques_juros"},{"└ Desconto de Juros","cheques_desconto"},{"📊 DRE","dre"},{"📘 Livro Caixa","mov"},{"📙 Livro Diário","lanc"},{"📗 Livro Razão","lanc"},{"📒 Balancete","plano_contas"},{"📦 Extrato de Estoque","estoque_movimentos"},{"🧮 Inventário / Ajuste","produtos"},{"📄 Relatórios","rel"},{"🔎 Auditoria","audit"},{"⇄ Importar base V045","importdb"},{"⬆ Exportar p/ computador","export"}};
  for(String[]x:m){TextView v=tv(x[0],16,Color.WHITE);v.setPadding(dp(14),dp(12),dp(6),dp(12));v.setBackgroundColor(NAVY);v.setOnClickListener(q->{drawer.setVisibility(View.GONE);route(x[1]);});list.addView(v,new LinearLayout.LayoutParams(-1,dp(52)));View line=new View(this);line.setBackgroundColor(Color.rgb(38,59,86));list.addView(line,new LinearLayout.LayoutParams(-1,1));}sv.addView(list);d.addView(sv,new LinearLayout.LayoutParams(-1,0,1));TextView ver=tv("VERSÃO V045",13,GOLD);ver.setTypeface(null,Typeface.BOLD);ver.setPadding(dp(14),dp(10),0,dp(10));d.addView(ver);return d;}
 void openDrawer(){drawer.setVisibility(drawer.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);drawer.bringToFront();}
 void clear(String h){content.removeAllViews();TextView t=tv(h,27,TEXT);t.setTypeface(null,Typeface.BOLD);t.setPadding(dp(8),dp(5),0,dp(16));content.addView(t);}
 void dashboard(){clear("Dashboard");LinearLayout row=null;String[][]cards={{"Receitas em aberto",money(db.scalar("SELECT COALESCE(sum(valor-valor_baixado),0) FROM titulos WHERE tipo='Receber' AND COALESCE(status,'Aberto') NOT IN ('Pago','Baixado')"))},{"Despesas em aberto",money(db.scalar("SELECT COALESCE(sum(valor-valor_baixado),0) FROM titulos WHERE tipo='Pagar' AND COALESCE(status,'Aberto') NOT IN ('Pago','Baixado')"))},{"Vendas hoje",money(db.scalar("SELECT COALESCE(sum(total),0) FROM vendas WHERE data=strftime('%d/%m/%Y','now','localtime') OR data=date('now','localtime')"))},{"Clientes",safeCount("clientes")+""},{"Fornecedores",safeCount("fornecedores")+""},{"Produtos",safeCount("produtos")+""},{"Boletos",safeCount("boletos")+""},{"Fiados",safeCount("fiado")+""}};
  for(int i=0;i<cards.length;i++){if(i%2==0){row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);content.addView(row,new LinearLayout.LayoutParams(-1,dp(116)));}row.addView(card(cards[i][0],cards[i][1]),new LinearLayout.LayoutParams(0,dp(102),1));}
  TextView ac=tv("Ações rápidas",20,TEXT);ac.setTypeface(null,Typeface.BOLD);ac.setPadding(dp(8),dp(14),0,dp(8));content.addView(ac);LinearLayout r=new LinearLayout(this);String[][]bs={{"Nova venda","vendas"},{"Nova despesa","pagar"},{"Nova receita","receber"}};for(String[]x:bs)r.addView(button(x[0],v->route(x[1])),new LinearLayout.LayoutParams(0,dp(52),1));content.addView(r);LinearLayout r2=new LinearLayout(this);r2.addView(button("Novo cliente",v->openTable("clientes","Clientes / Participantes")),new LinearLayout.LayoutParams(0,dp(52),1));r2.addView(button("Novo produto",v->openTable("produtos","Produtos / Estoque")),new LinearLayout.LayoutParams(0,dp(52),1));content.addView(r2);
 }
 long safeCount(String t){try{return db.count(t);}catch(Exception e){return 0;}} String money(double v){return NumberFormat.getCurrencyInstance(new Locale("pt","BR")).format(v);}
 View card(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(8),dp(10));GradientDrawableX.round(c,Color.WHITE,16);TextView x=tv(a,14,MUTED);TextView y=tv(b,22,TEXT);y.setTypeface(null,Typeface.BOLD);c.addView(x);c.addView(y);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(102),1);p.setMargins(dp(5),dp(5),dp(5),dp(5));c.setLayoutParams(p);return c;}
 TextView button(String s,View.OnClickListener l){TextView b=tv(s,14,Color.WHITE);b.setTypeface(null,Typeface.BOLD);b.setGravity(Gravity.CENTER);b.setOnClickListener(l);GradientDrawableX.round(b,NAVY,10);b.setPadding(dp(6),0,dp(6),0);return b;}
 void route(String k){try{if(k.equals("dash")){dashboard();return;}if(k.equals("importdb")){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),700);return;}if(k.equals("export")){exportJson();return;}if(k.equals("pagar")){openFilteredTitles("Pagar");return;}if(k.equals("receber")){openFilteredTitles("Receber");return;}if(k.equals("dre")){dre();return;}if(k.equals("rel")){reports();return;}if(k.equals("audit")){audit();return;}if(k.equals("lanc")){openTable("movimentos_contas_financeiras","Lançamentos Integrados");return;}if(k.equals("mov")){openTable("movimentos_contas_financeiras","Livro Caixa");return;}openTable(k,titleFor(k));}catch(Exception e){toast("Função indisponível nesta base: "+e.getMessage());}}
 String titleFor(String k){return k.replace('_',' ').toUpperCase(new Locale("pt","BR"));}
 void openFilteredTitles(String tipo){openTableQuery("titulos",tipo.equals("Pagar")?"Contas a Pagar":"Contas a Receber","tipo=?",new String[]{tipo});}
 void openTable(String table,String heading){openTableQuery(table,heading,null,null);}
 void openTableQuery(String table,String heading,String where,String[]args){clear(heading);LinearLayout tools=new LinearLayout(this);tools.addView(button("+ NOVO",v->editDialog(table,null)),new LinearLayout.LayoutParams(0,dp(48),1));tools.addView(button("ATUALIZAR",v->openTableQuery(table,heading,where,args)),new LinearLayout.LayoutParams(0,dp(48),1));content.addView(tools);SQLiteDatabase d=db.getReadableDatabase();Cursor c=d.query(table,null,where,args,null,null,"id DESC","150");String[]cols=c.getColumnNames();while(c.moveToNext()){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(8),dp(12),dp(8));GradientDrawableX.round(box,Color.WHITE,10);StringBuilder sb=new StringBuilder();int id=-1;for(int i=0;i<Math.min(cols.length,8);i++){if(cols[i].equals("id"))id=c.getInt(i);else{String val=c.isNull(i)?"":c.getString(i);if(val!=null&&!val.isEmpty())sb.append(cols[i]).append(": ").append(val).append("\n");}}TextView tx=tv(sb.toString().trim(),13,TEXT);box.addView(tx);final int fid=id;box.setOnClickListener(v->editDialog(table,fid));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));content.addView(box,p);}c.close();}
 void editDialog(String table,Integer id){SQLiteDatabase d=db.getWritableDatabase();Cursor meta=d.rawQuery("PRAGMA table_info("+table+")",null);ArrayList<String> cols=new ArrayList<>();while(meta.moveToNext()){String n=meta.getString(1);if(!n.equals("id"))cols.add(n);}meta.close();HashMap<String,String> old=new HashMap<>();if(id!=null){Cursor c=d.query(table,null,"id=?",new String[]{id+""},null,null,null);if(c.moveToFirst())for(String n:cols){int ix=c.getColumnIndex(n);if(ix>=0&&!c.isNull(ix))old.put(n,c.getString(ix));}c.close();}
  ScrollView sv=new ScrollView(this);LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(16),dp(6),dp(16),dp(6));HashMap<String,EditText> fields=new HashMap<>();for(String n:cols){EditText e=new EditText(this);e.setHint(n);e.setText(old.getOrDefault(n,""));e.setTextSize(14);form.addView(e,new LinearLayout.LayoutParams(-1,dp(58)));fields.put(n,e);}sv.addView(form);AlertDialog dlg=new AlertDialog.Builder(this).setTitle(id==null?"Novo registro":"Editar registro #"+id).setView(sv).setPositiveButton("SALVAR",null).setNegativeButton("CANCELAR",null).create();dlg.setOnShowListener(x->dlg.getButton(-1).setOnClickListener(v->{try{ContentValues cv=new ContentValues();for(String n:cols){String z=fields.get(n).getText().toString();cv.put(n,z);}if(id==null)d.insertOrThrow(table,null,cv);else d.update(table,cv,"id=?",new String[]{id+""});dlg.dismiss();route(table.equals("titulos")?"dash":table);}catch(Exception ex){toast(ex.getMessage());}}));dlg.show();}
 void dre(){clear("DRE");double rec=db.scalar("SELECT COALESCE(sum(valor),0) FROM movimentos_contas_financeiras WHERE lower(tipo) LIKE '%rece%' OR lower(tipo) LIKE '%entr%'");double des=db.scalar("SELECT COALESCE(sum(valor),0) FROM movimentos_contas_financeiras WHERE lower(tipo) LIKE '%desp%' OR lower(tipo) LIKE '%saí%' OR lower(tipo) LIKE '%sai%'");content.addView(card("Receitas",money(rec)));content.addView(card("Despesas",money(des)));content.addView(card("Resultado",money(rec-des)));}
 void reports(){clear("Relatórios");String[] a={"DRE","Livro Caixa","Contas a Receber","Contas a Pagar","Produtos / Estoque","Clientes","Fornecedores","Boletos","Fiado"};for(String x:a){TextView b=button(x,v->{String s=((TextView)v).getText().toString();if(s.equals("DRE"))dre();else if(s.contains("Receber"))openFilteredTitles("Receber");else if(s.contains("Pagar"))openFilteredTitles("Pagar");else if(s.contains("Produtos"))openTable("produtos",s);else if(s.equals("Clientes"))openTable("clientes",s);else if(s.equals("Fornecedores"))openTable("fornecedores",s);else if(s.equals("Boletos"))openTable("boletos",s);else if(s.equals("Fiado"))openTable("fiado",s);else openTable("movimentos_contas_financeiras",s);});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(5),0,dp(5));content.addView(b,p);}}
 void audit(){clear("Auditoria");String[] tabs={"clientes","fornecedores","produtos","bancos","plano_contas","centros_custo","titulos","boletos","fiado","vendas","estoque_movimentos"};for(String t:tabs){TextView v=tv("✓ "+t+": "+safeCount(t)+" registros",15,TEXT);v.setPadding(dp(10),dp(10),0,dp(10));content.addView(v);}TextView v=tv("Banco: "+getDatabasePath(DB.NAME).getAbsolutePath(),12,MUTED);content.addView(v);}
 void exportJson(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"CONTA_CERTA_LANCAMENTOS_V1_"+System.currentTimeMillis()+".json");startActivityForResult(i,701);}
 void writeJson(Uri u)throws Exception{JSONObject out=new JSONObject();out.put("formato","CONTA_CERTA_LANCAMENTOS_V1");out.put("dispositivo", Settings.Secure.getString(getContentResolver(),Settings.Secure.ANDROID_ID));out.put("exportado_em",new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.US).format(new Date()));JSONArray arr=new JSONArray();Cursor c=db.getReadableDatabase().rawQuery("SELECT id,tipo,pessoa,documento,emissao,vencimento,valor,observacao FROM titulos WHERE origem='android' OR origem IS NULL ORDER BY id",null);while(c.moveToNext()){JSONObject r=new JSONObject();r.put("uuid",UUID.nameUUIDFromBytes(("titulo:"+c.getInt(0)).getBytes()).toString());r.put("tipo","Receber".equalsIgnoreCase(c.getString(1))?"conta_receber":"conta_pagar");r.put("data",c.getString(4));r.put("vencimento",c.getString(5));r.put("pessoa_nome",c.getString(2));r.put("documento",c.getString(3));r.put("historico",c.getString(7));r.put("valor",c.getDouble(6));arr.put(r);}c.close();out.put("lancamentos",arr);try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(out.toString(2).getBytes("UTF-8"));}toast("Arquivo exportado com "+arr.length()+" lançamentos.");}
 protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(c!=RESULT_OK||data==null)return;try{if(r==700){try(InputStream in=getContentResolver().openInputStream(data.getData())){db.replaceDatabase(in);}db=new DB(this);toast("Base V045 importada. Dashboard atualizado.");dashboard();}else if(r==701)writeJson(data.getData());}catch(Exception e){toast("Erro: "+e.getMessage());}}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 public void onBackPressed(){if(drawer.getVisibility()==View.VISIBLE){drawer.setVisibility(View.GONE);return;}dashboard();}
}
class GradientDrawableX{static void round(View v,int color,float radius){android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(color);g.setCornerRadius(radius*v.getResources().getDisplayMetrics().density);v.setBackground(g);}}
